### ISSUE TITLE
Date shown incorrectly on post event

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/data-donuts#139]
Our speaker reached out to let us know that the data on our Data + Donuts website is wrong. Currently it is showing:

![Screenshot 2024-09-24 at 12 02 10 PM](https://github.com/user-attachments/assets/94191f56-88e9-4ffd-b3b8-33bd751241f5)

But in the Github Repo under src > _posts > `2024-09-26-data-donuts-44.md` it shows that it should start on 9/26

![Screenshot 2024-09-24 at 12 03 48 PM](https://github.com/user-attachments/assets/53f40cb7-7353-4e9c-a337-5e811106e6b1)

**Comment by angela-tran** [comment]
A quick fix was done here: https://github.com/compilerla/data-donuts/pull/141

We may want to investigate our config further to confirm if this is the right fix or not

**Comment by thekaveman** [comment]
I think the underlying issue is probably that [date line](https://github.com/compilerla/data-donuts/blob/main/src/_posts/2024-09-26-data-donuts-44.md?plain=1#L6) being in UTC+8, when we are in UTC-7 right now.

```yaml
---
layout: post

#event information
title:  "Building a Data Science Community"
date:   2024-09-26 08:00+0800
```
